### ISSUE TITLE
interactive-execution: run interactive web notebooks

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-workflow-controller#178]
Currently, REANA only supports running [batch workflows](https://github.com/reanahub/reana-workflow-controller/blob/master/reana_workflow_controller/workflow_run_manager.py#L168). We want now to add the functionality to run interactive notebooks, meaning that users would be able to attach to a notebook running inside REANA and be able to use its computing power remotely. To implement that we need:

- [x] Install Traefik on Minikube (R-Cluster)
- [x] Implement the creation of interactive pods (R-W-Controller)
- [x] Implement the logic to expose the dynamically created pods (R-W-Controller)
- [ ] Protect interactive session, an option with Jupyter is to return [the autogenerated token](https://jupyter-notebook.readthedocs.io/en/stable/security.html#security-in-the-jupyter-notebook-server). It would be great if we could configure the Notebook to instead of autogenerating the token, to use the REANA user token.
- [ ] Solve redirect issue see https://github.com/reanahub/reana-workflow-controller/issues/178#issuecomment-461341399.
- [ ] Mount workflow workspace inside the interactive session pod.
- [ ] Provide a way to stop interactive sessions (e.g. `reana-client close workflow.1`)
- [ ] Gargabe collect all intactive interactive sessions (overall execution time policy, `cronjob` maybe, and no traffic policy for example, some native garbage collector similar to [TTL mechanism for finished jobs](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#ttl-mechanism-for-finished-jobs))
- [ ] REANA Cluster needs rewrite to retrieve the API Server URL, connects with https://github.com/reanahub/reana-cluster/issues/73.

**Comment by tiborsimko** [comment]
... plus enrich `reana.yaml` so that user can specify which web ports are to be opened for access, and eventually for how long the pod should stay on before garbage collection hits in. These will be treated separately.

**Comment by diegodelemos** [comment]
This PR group needs a first code review only and once amended and completed can be tested. 

If you want to test it either way, you need:
- https://github.com/reanahub/reana-cluster/pull/155 to spawn the cluster
- https://github.com/reanahub/reana-client/pull/245, https://github.com/reanahub/reana-server/pull/120 and https://github.com/reanahub/reana-workflow-controller/pull/179 with https://github.com/reanahub/reana-commons/pull/88 installed.
```console
$ pip install git+https://github.com/diegodelemos/reana-commons@r-w-c-178-interactive-notebooks-openapi-specs -U
```
#### Current status
```console
$ reana-cluster env --include-admin-token
export REANA_SERVER_URL=http://192.168.99.100:31475
export REANA_ACCESS_TOKEN=supersecrettoken
$ export REANA_ACCESS_TOKEN=supersecrettoken
$ # REANA Server URL port needs to be updated since we are setting the port of Traefik
$ # to be 30080 see https://github.com/reanahub/reana-cluster/pull/153/files#diff-fa1e10a0359d03b37c15961dfe7d2174R13
$ export REANA_SERVER_URL=http://192.168.99.100:30080
$ reana-client ping
Connected to http://192.168.99.100:30080 - Server is running.
$ rc create
workflow.1
$ rc open workflow.1
http://192.168.99.100:30080/ece74f53-7ea1-4c38-9458-67be4f3ef121
```
Until here you would get:
![image](https://user-images.githubusercontent.com/9035606/52400677-17080600-2ac0-11e9-924f-89238f66cf3c.png)
Because the token autogenerated by Jupyter is not included (It can be retrieved with `kubectl logs interactive-process-____`):
```console
$ kubectl logs interactive-process-ece74f53-7ea1-4c38-9458-67be4f3ef121-5bhvss | head
Executing the command: jupyter notebook
[I 08:51:59.926 NotebookApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
[I 08:52:00.227 NotebookApp] JupyterLab extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab
[I 08:52:00.227 NotebookApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 08:52:00.228 NotebookApp] Serving notebooks from local directory: /home/jovyan
[I 08:52:00.228 NotebookApp] The Jupyter Notebook is running at:
[I 08:52:00.229 NotebookApp] http://(interactive-process-ece74f53-7ea1-4c38-9458-67be4f3ef121-5bhvss or 127.0.0.1):8888/?token=jupytergeneratedsecrettoken
[I 08:52:00.229 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 08:52:00.229 NotebookApp]
$ http $REANA_SERVER_URL/ece74f53-7ea1-4c38-9458-67be4f3ef121/?token=jupytergeneratedsecrettoken
HTTP/1.1 302 Found
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Date: Thu, 07 Feb 2019 09:08:47 GMT
Location: /ece74f53-7ea1-4c38-9458-67be4f3ef121/?token=3c5a50e209acdc2cf7cf45348c5cbd7339c4b690be7dc0ba
Server: TornadoServer/5.1.1
Vary: Accept-Encoding
```
Which in the browser results in:
![image](https://user-images.githubusercontent.com/9035606/52400869-a9100e80-2ac0-11e9-864c-da326abef80d.png)
