### ISSUE TITLE
CMSSW needs local SITECONFIG in CVMFS

### ISSUE THREAD

**Issue by clelange** [reanahub/reana-workflow-controller#238]
When running CMSSW using releases in CVMFS, one currently gets the following error message using reana hub:

```shell
----- Begin Fatal Exception 08-Aug-2019 15:42:20 CEST-----------------------
An exception of category 'Incomplete configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing ESSource: class=PoolDBESSource label='GlobalTag'
Exception Message:
Valid site-local-config not found at /cvmfs/cms.cern.ch/SITECONF/local/JobConfig/site-local-config.xml
----- End Fatal Exception -------------------------------------------------
```

In order to to fix this, there needs to be a soft link in the following form:

```shell
ls -l /cvmfs/cms.cern.ch/SITECONF/local
lrwxrwxrwx. 1 cvmfs cvmfs 10 Sep 19  2017 /cvmfs/cms.cern.ch/SITECONF/local -> T2_CH_CERN
```

This could also point to other configs, e.g. `T3_CH_CERN_OpenData` or `T3_CH_Volunteer`, to be tested. Creating the directory/file structure in the analysis container doesn't help, since it's replaced by the CSI plugin.

Technically, I guess there should just be a `subPath` mount in addition to the standard `cms.cern.ch` mount, somehow like this:

```yaml
- name: siteconfigs
  mountPath: /cvmfs/cms.cern.ch/SITECONF/
  subPath: local
```

See https://twiki.cern.ch/twiki/bin/view/CMSPublic/CernVMFS4cms and https://twiki.cern.ch/twiki/bin/view/CMSPublic/SiteConfInGitlab for more background information.

**Comment by roksys** [comment]
@clelange 

Possible workaround would be the following:

1. $ CMS_PATH=~/work
2. $ mkdir $CMS_PATH/SITECONF/local
3. $ cp -r /cvmfs/cms.cern.ch/SITECONF/<insert_site_name>/*  $CMS_PATH/SITECONF/local/
4. $ ll $CMS_PATH/SITECONF/local/JobConfig/site-local-config.xml

I haven't tested it now, but I was using this workaround a few years ago.

**Comment by roksys** [comment]
@clelange,

I and @diegodelemos just tried additional volume mount with `subPath: local`. Unfortunately it doesn't work, since CVMFS is `persistentVolumeClaim` and has no `path`. 

I can confirm that a workaround I posted earlier is 100 % working, I just tried it with random SITECONF. Have you tried it?

**Comment by diegodelemos** [comment]
Waiting for answer in https://cern.service-now.com/service-portal/view-incident.do?n=INC2095130.

**Comment by tiborsimko** [comment]
See @clelange's test in https://gitlab.cern.ch/clange/cms-cvmfs-csi that @rochaporto would look at deploying centrally so that the CMSSW/CVMFS setup would work centrally for REANA, GitLab, and any other cluster at CERN.

**Comment by tiborsimko** [comment]
Works on GitLab; need to check central templates.

**Comment by diegodelemos** [comment]
This is integrated in the central CERN templates, thanks to @rochaporto and @clelange see https://its.cern.ch/jira/browse/OS-10494. We will recreate first QA to make sure it works and them production.
