### ISSUE TITLE
WORKFLOW_RUNTIME_USER_GID only works if GID already exists in container

### ISSUE THREAD

**Issue by khurtado** [reanahub/reana-workflow-controller#247]
The following line tries to create a user with a specific ID/GID. The problem is that `-g` only works if the `gid` already exists.

https://github.com/reanahub/reana-workflow-controller/blob/5e31c1536db56898542c1d9abca42451a0507d93/reana_workflow_controller/workflow_run_manager.py#L446

**Comment by roksys** [comment]
Hi @khurtado,

Thanks for reporting it. PR #248 should solve it.
