### ISSUE TITLE
k8s: auto-discover appropriate runtime UID/GID

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-workflow-controller#269]
### The problem

Currently when workflow controller starts a workflow engine instance to run workflow for a given user on Kubernetes, we are forcing some static user name, UID and GID values taken from ``reana-commons``: 

```
reana_commons/config.py-140-WORKFLOW_RUNTIME_USER_NAME = os.getenv(
reana_commons/config.py-141-    'WORKFLOW_RUNTIME_USER_NAME',
reana_commons/config.py-142-    'reana')
reana_commons/config.py-143-"""Default OS user name for running job controller."""
reana_commons/config.py-144-
reana_commons/config.py-145-WORKFLOW_RUNTIME_USER_UID = os.getenv(
reana_commons/config.py-146-    'WORKFLOW_RUNTIME_USER_UID',
reana_commons/config.py:147:    1000)
reana_commons/config.py-148-"""Default user id for running job controller/workflow engine apps & jobs."""
reana_commons/config.py-149-
reana_commons/config.py-150-WORKFLOW_RUNTIME_USER_GID = os.getenv(
reana_commons/config.py-151-    'WORKFLOW_RUNTIME_USER_GID',
reana_commons/config.py-152-    0)
reana_commons/config.py-153-"""Default group id for running job controller/workflow engine apps & jobs."""
```

In some cases, the user container may force some user identity, in which case the workflows fail, see ATLAS RECAST example: https://github.com/reanahub/reana-demo-atlas-recast/pull/22#issuecomment-560488019 

REANA needs to respect user ID in this case.

### The solution

One possibility is to try to auto-discover UID/GID wanted by the user.

(1) Parse the wanted computational workflow, take its first step, and discover which Docker image this step uses.
 
(2) Use this Docker image to discover the which user is the default:

```
$ docker run -i -t --rm reanahub/reana-demo-atlas-recast-eventselection /usr/bin/id
uid=500(atlas) gid=500(atlas) groups=500(atlas),0(root)
```
(3) Detect what would be an appropriate REANA user via rules such as these:

- If image uses a certain UID and GID greater than 100, use those.
- If image uses root rights and/or UID/GID less than 100, force current WORKFLOW_RUNTIME_USER_UID defaults (i.e. uid=1000) for security.
- If image uses a user that does not belong to GID=0 group, warn the user that this may lead to problems with writing to shared directories.

(4) Start the workflow instance with the auto-detected UID/GID.

### Notes

- Once the UID/GID will be auto-discovered by the REANA-Workflow-Controller, we can move the static values away from ``reana-commons``.

- In theory, the file upload could be done under the same user identity, so that the files seeding the workspace have the same ownership as the files created during workflow run.  In practice, the seeded files should be mostly R/O, so we can leave this out for now.

**Comment by roksys** [comment]
> ### Notes
> * Once the UID/GID will be auto-discovered by the REANA-Workflow-Controller, we can move the static values away from `reana-commons`.

I'm not sure if this the right way, because these values are not only used in RWC but as well in [RJC](https://github.com/reanahub/reana-job-controller/blob/104556b82dd626c608166964e7ee144e2b247b05/reana_job_controller/kubernetes_job_manager.py#L159). Default static values can be easily overwritten by env variables.

**Comment by tiborsimko** [comment]
> I'm not sure if this the right way, because these values are not only used in RWC but as well in RJC. Default static values can be easily overwritten by env variables.

Presumably RJC will just accept "orders" from RWC who will decide on some UID/GID values?! Could be passed as mandatory arguments...  Anyway it is a minor point where to keep the defaults, we can see better once the initial implementation is started.

**Comment by tiborsimko** [comment]
BTW I have just run a quick test with Kerberos-aware workflows on Kubernetes and it seems that we are still using UID=1000, GID=0 for this use case too. Something to remember in case this might lead to troubles later if people would like to use their Kerberos rights for writing to EOS or somesuch.

```console
$ cat reana.yaml
workflow:
  type: serial
  specification:
    steps:
      - environment: 'python:2.7-slim'
        kerberos: true
        commands:
        - id > output.txt
$ reana-client run -w krb5
$ reana-client download output.txt -w krb5
$ cat output.txt
uid=1000 gid=0(root) groups=0(root)
```

**Comment by lukasheinrich** [comment]
yes this should probably be decided by the engine (since it's more or less similar to deciding the image etc..)

**Comment by roksys** [comment]
Solved by https://github.com/reanahub/reana-workflow-controller/pull/271
