### ISSUE TITLE
yadage: add option to submit workflow file instead of grabbing it from GitHub

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-workflow-controller#31]

**Comment by tiborsimko** [comment]
This issue is interesting e.g. for @atrisovic's use case regarding LHCb data production that will use a fixed Docker image, a fixed set of workflow steps, and a dynamically detected set of variables as input for this workflow. I.e. there should be no need for Yadage to read some GitHub source code repository, as in the case of an analyses, because here there isn't one...

**Comment by atrisovic** [comment]
Please @lukasheinrich can you have a look at this. I would really like to try out what Tibor mentioned.

**Comment by diegodelemos** [comment]
Closed as implemented in:

Workflow example: https://github.com/reanahub/reana-demo-root6-roofit/pull/2
REANA Client `cli` changes: https://github.com/reanahub/reana-client/pull/9
REANA Server API changes: https://github.com/reanahub/reana-server/pull/9
REANA Workflow controller API changes: https://github.com/reanahub/reana-workflow-controller/pull/32
REANA Workflow Engine Yadage change: https://github.com/reanahub/reana-workflow-engine-yadage/pull/35 (using https://github.com/diegodelemos/yadage/commit/3bb0a1b2e1cbe91c20f69560ea1d6193b5d60b20)

Assuming that REANA is properly installed and updated with latest REANA Server, REANA Workflow Controller and REANA Workflow Engine Yadage:
```console
$ mkvirtualenv reana-client
$ pip install git+https://github.com/reanahub/reana-client.git pyOpenSSL rfc3987 webcolors strict-rfc3339
$ export REANA_SERVER_URL=http://reana.cern.ch # use `reana get reana-server` to get IP:port
$ git clone https://github.com/reanahub/reana-demo-root6-roofit/
$ cd reana-demo-root6-roofit
$ reana-client run
[INFO] REANA Server URL set to: http://reana.cern.ch
[INFO] Connecting to http://reana.cern.ch
{u'message': u'Workflow successfully launched', u'workflow_id': u'2ecd10fc-2f7f-46b2-91cf-d7ab577c6009'}
$ firefox http://reana-monitor.cern.ch/2ecd10fc-2f7f-46b2-91cf-d7ab577c6009 # `reana get reana-workflow-monitor`
```
