### ISSUE TITLE
db: workflow controller fails to initialise when restarted

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-workflow-controller#33]
**Problem**
When an instance of `reana-workflow-controller` gets restarted, it tries to [recreate the default user](https://github.com/reanahub/reana-workflow-controller/blob/master/Dockerfile#L27) but because the previous container created it, it crashes
```console
$ kubectl logs workflow-controller-4113089262-g8z27 -p
/usr/local/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py:819: UserWarning: SQLALCHEMY_DATABASE_URI not set. Defaulting to "sqlite:///:memory:".
  'SQLALCHEMY_DATABASE_URI not set. Defaulting to '
Usage: flask users create [OPTIONS] EMAIL

Error: Invalid value for id_: User with id=00000000-0000-0000-0000-000000000000 already exists.
```

**Solution**
Check if user exists on `flask users create`

thanks to @anton-khodak for spotting the problem

**Comment by tiborsimko** [comment]
This could be solved by amending `users_create_default()` to check whether the default user is already there... A kind of doing SELECT first, and if the user not there, INSERT him/her.
