### ISSUE TITLE
quotas: calculate quota usage for workflows and store them

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-workflow-controller#332]
Fill the new fields/table created in https://github.com/reanahub/reana-db/issues/83.

- CPU: We could use the [existing information about workflow start, stop/finished](https://github.com/reanahub/reana-db/blob/c89d3703b8bcae2f8af83f6c81473b201e1997a0/reana_db/models.py#L255-L257)
    - Note we shouldn't allow deletion of CPU usage
- HDD: RWC has full access to the workflow workspace
    - It should store the workspace disk usage in DB after the workflow finishes
    - The disk usage would be updated every night?

**Comment by tiborsimko** [comment]
See also https://github.com/reanahub/reana-workflow-controller/issues/333#issuecomment-696627891 about updating DB numbers via several triggers
