### ISSUE TITLE
files: recalculate quota on file upload/deletion

### ISSUE THREAD

**Issue by mvidalgarcia** [reanahub/reana-workflow-controller#339]
Recalculate quota as in update both `WorkflowResource.quantity_used` and `UserResource.quota_used` for CPU and disk.

File upload/deletion (`reana-client rm`/`reana-client upload`) -> we can run the full calculation for now but, this can become dangerous:
    - Doing this calculation on every upload could be a very expensive server-side operation, as we [upload each file on a different HTTP request](https://github.com/reanahub/reana-client/blob/577e5dd52f14a75bed32863ccbd419e6c2ebac0d/reana_client/cli/files.py#L277).
    - We know how big those files are when uploaded, so in theory we can just increment/decrement the disk usage by the number of bytes the files occupy at workflow and user level.

_Originally posted by @diegodelemos in https://github.com/reanahub/reana-db/pull/92#discussion_r501686934_

**Comment by diegodelemos** [comment]
Tested locally, all working great!
- Changelogs to be updated
- Minor comments
- [Small issue observed](https://github.com/reanahub/reana-server/pull/317/files#r524042838) which needs to be reproduced, perhaps in a different issue to not stop this from merging, what do you think @mvidalgarcia?

**Comment by mvidalgarcia** [comment]
> Tested locally, all working great!
> 
>     * Changelogs to be updated
> 
>     * Minor comments
> 
>     * [Small issue observed](https://github.com/reanahub/reana-server/pull/317/files#r524042838) which needs to be reproduced, perhaps in a different issue to not stop this from merging, what do you think @mvidalgarcia?

I think all the comments are addressed now. I'll push r-db release to make r-w-c test pass.
About the r-server issue. I agree this can be part of a separate issue as it looks related to `requests` connections, unless we find a quick solution we can immediately apply.
