### ISSUE TITLE
api: add support for `reana-workflow-engine-cwl`

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-workflow-controller#34]
Once the [REANA Workflow Engine CWL](https://github.com/reanahub/reana-workflow-engine-cwl/issues) is ready (celery task is defined, see [yadage example](https://github.com/reanahub/reana-workflow-engine-yadage/blob/master/reana_workflow_engine_yadage/tasks.py#L89)) we should connect to it creating a new endpoint and adding the celery task (see yadage [endpoint](https://github.com/reanahub/reana-workflow-controller/blob/master/reana_workflow_controller/rest.py#L150) and [celery task](https://github.com/reanahub/reana-workflow-controller/blob/master/reana_workflow_controller/tasks.py#L41))

**Comment by anton-khodak** [comment]
Should we create a similar issue for reana-workflow-monitor (see https://github.com/reanahub/reana-workflow-monitor/blob/e2e26419c680eb05a95b272f0d3e0410b1c25342/server/app.py#L48)?

**Comment by tiborsimko** [comment]
Closed by #67.
