### ISSUE TITLE
get_current_job_progress is making a lot of unnecessary DB queries

### ISSUE THREAD

**Issue by VMois** [reanahub/reana-workflow-controller#416]
It looks like [get_current_job_progress](https://github.com/reanahub/reana-workflow-controller/blob/d650d0c059ff17bd3b62d5e34addfa1af9e24c1c/reana_workflow_controller/rest/utils.py#L172) function is doing too many queries for each workflow:

https://github.com/reanahub/reana-workflow-controller/blob/d650d0c059ff17bd3b62d5e34addfa1af9e24c1c/reana_workflow_controller/rest/utils.py#L172-L188

After a single query to get *all* jobs, for each job from previous results a new query is performed to get the same job Assuming `id_` for each job is unique, even for retried ones, this is not optimal behavior.

Maybe, an additional job query has some purpose but, unfortunately, context is lost.

Originated from #415

**Comment by VMois** [comment]
A quick look into [Job DB model](https://github.com/reanahub/reana-db/blob/9734af69f57e5ec425150c690552f8c179681343/reana_db/models.py#L739), `id_` is a primary key so unique.

**Comment by mvidalgarcia** [comment]
All the logic here it's (supposedly) needed just to be able to print the command of the last step when calling `reana-client status` with the `verbose` flag.

```console
$ reana-client status -w roofit -v
NAME     RUN_NUMBER   CREATED               STARTED               ENDED                 STATUS     PROGRESS   ID                                     USER                                   COMMAND                                                            
roofit   1            2021-11-03T14:51:13   2021-11-03T14:51:27   2021-11-03T14:51:43   finished   2/2        7b18ac68-7714-4a01-81d1-d53e900b3e91   00000000-0000-0000-0000-000000000000   root -b -q 'code/fitdata.C("results/data.root","results/plot.png")'
```

or if the command doesn't exist, print the job name.

```console
$ reana-client status -w roofit -v
NAME     RUN_NUMBER   CREATED               STARTED               ENDED                 STATUS     PROGRESS   ID                                     USER                                   COMMAND
roofit   1            2021-11-03T14:51:13   2021-11-03T14:51:27   2021-11-03T14:51:43   finished   2/2        7b18ac68-7714-4a01-81d1-d53e900b3e91   00000000-0000-0000-0000-000000000000   fitdata
```
(Note the wrong header)

This information isn't used anywhere else and we're querying it every time we call `/api/workflows?verbose=True`, which is always in the case of [UI queries](https://github.com/reanahub/reana-ui/blob/b375b3a3531c6eb0593339333dcb6bf2a2e0f341/reana-ui/src/actions.js#L81) for instance, and probably in other places when passing `include_progress=True`

In addition, it's not 100% sure that the code is fetching the last job command as [here](https://github.com/reanahub/reana-workflow-controller/blob/d650d0c059ff17bd3b62d5e34addfa1af9e24c1c/reana_workflow_controller/rest/utils.py#L176-L187) we save **all** the jobs and we rely directly on [`dict.popitem()`](https://github.com/reanahub/reana-workflow-controller/blob/d650d0c059ff17bd3b62d5e34addfa1af9e24c1c/reana_workflow_controller/rest/utils.py#L639) to get the most recent one, which is not guaranteed as it's not an OrderedDict.

Some questions arise:
- Is it essential to display this information in `reana-client status`?
- Is it worth keeping this convoluted logic/expensive logic ([[1]](https://github.com/reanahub/reana-workflow-controller/blob/d650d0c059ff17bd3b62d5e34addfa1af9e24c1c/reana_workflow_controller/rest/utils.py#L172-L188), [[2]](https://github.com/reanahub/reana-client/blob/d0e46eb5dd6efce5e4e91aeab81bd4c21c9e1532/reana_client/cli/workflow.py#L687-L709)) just to display the "current command" or the "current job name"?

**Comment by mvidalgarcia** [comment]
So far, I'm keeping the same behavior but optimizing the affected parts ([PR](https://github.com/reanahub/reana-workflow-controller/pull/418)). In case we want to get rid of the logic mentioned [here](https://github.com/reanahub/reana-workflow-controller/issues/416#issuecomment-959714780), it can be addressed separately.
