### ISSUE TITLE
sanitise compute_backend workflow hints early

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-workflow-controller#424]
**Current behaviour**

If a REANA cluster uses `REANA_RUNTIME_KUBERNETES_KEEP_ALIVE_JOBS_WITH_STATUSES` set to `failed`, and user asks to run the workflow on computer backend that is not supported, then there are runaway `NotReady` pods. See #401 for the details on how to trigger this problem.

**Expected behaviour**

If a user asks to run a workflow on a compute backend that is not supported, such a workflow should not have been accepted in the first place.

Let's do the workflow parameter sanitisation early.

For example, we have validation checking for remote cluster server capabilities:

```console
$ reana-client validate -f ./reana-slurmcern.yaml --server-capabilities
==> Verifying REANA specification file... /home/tibor/private/project/reana/src/reana-demo-root6-roofit/reana-slurmcern.yaml
  -> SUCCESS: Valid REANA specification file.
==> Verifying REANA specification parameters...
  -> SUCCESS: REANA specification parameters appear valid.
==> Verifying workflow parameters and commands...
  -> SUCCESS: Workflow parameters and commands appear valid.
==> Verifying dangerous workflow operations...
  -> SUCCESS: Workflow operations appear valid.
==> Verifying workspace in REANA specification file...
  -> WARNING: Workspace not found in REANA specification file. Validation skipped.
```

Here, the remote server where the client is connected to does not support Slurm backend, so the validation should fail.

This workflow should not be accepted for execution.

**Notes**

Currently, users can enquire about REANA cluster capabilities via:

```console
$ reana-client info
Default workspace: /var/reana
List of available workspaces: /var/reana
```

or in the JSON format:

```console
$ reana-client info --json | jq
{
  "default_workspace": {
    "title": "Default workspace",
    "value": "/var/reana"
  },
  "workspaces_available": {
    "title": "List of available workspaces",
    "value": [
      "/var/reana"
    ]
  }
}
```

We only show the workspace options here.  As discussed during the introduction of `info` feature, we could show all the interesting server capabilities here, such as the list of supported compute backends. For example:

```json
{
    "compute_backends": {
        "title": "List of supported compute backends",
        "values": [
            "kubernetes",
            "htcondorcern"
        ]
    }
}
```

The validation could then check against those.

This means that the sucessful solution of the issue should do two things: (i) such a workflow would not be accepted for execution on the cluster side, so that htere are no `NotReady` pods hanging forever for those installations that use `REANA_RUNTIME_KUBERNETES_KEEP_ALIVE_JOBS_WITH_STATUSES` set to `failed`; (ii) such a workflow would not pass user validation when `validatie --server-capabilities` option is on.

**Comment by mvidalgarcia** [comment]
Do you have any idea of how to fetch the available compute backends from `reana-server` or `reana-workflow-controller`?

**Comment by tiborsimko** [comment]
(1) A "dirty" way would be to consult which image is used, and analyse available backends in that image:

```console
$ kubectl exec -i -t deployment/reana-workflow-controller -c rest-api -- /bin/bash -c 'env | grep REANA_JOB_CONTROLLER_IMAGE'
REANA_JOB_CONTROLLER_IMAGE=reanahub/reana-job-controller-htcondorcern-slurmcern:0.8.0

$ docker run --rm -i -t reanahub/reana-job-controller /bin/bash -c 'env | grep COMPUTE_BACKENDS'
COMPUTE_BACKENDS=kubernetes

$ docker run --rm -i -t reanahub/reana-job-controller-htcondorcern-slurmcern:0.8.0 /bin/bash -c 'env | grep COMPUTE_BACKENDS'
COMPUTE_BACKENDS=kubernetes,slurmcern,htcondorcern
```

This is obviously not "straightforward" to do during runtime and would require spawning a custom job to detect this. 

An easy first approximation alternative could be to judge by image name convention, e.g. if `reanahub/reana-job-controller-htcondorcern-slurmcern` is used then this indicates K8S/HTC/HPC, if `reanahub/reana-job-controller` is used then this indicates only K8S, only.

(2) A "clean" way would be to expose compute backend selection choice to the cluster admins via Helm configuration value, and read it from there. This is easier and could come handy e.g. if HPC does not work, we could temporarily disable it by tweaking Helm value and redeploying. 

But this could also bring its own set of small problems, e.g. what if admins allow HTCondor but use "wrong" image that does not have it built-in.  (I guess we could treat it as cluster admin human error then.)
