### ISSUE TITLE
interactive sessions: troubles connecting to notebook server

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-workflow-controller#457]
Opening new interactive sessions seems OK on recent master source code base using Kind 0.14:

![nb0](https://user-images.githubusercontent.com/517546/174779995-e7906891-2381-49de-b172-6eae3490ac1c.png)

But actually trying to open the notebook and run some Python code there seem to lead to troubles:

![nb1](https://user-images.githubusercontent.com/517546/174779521-59f2d9ff-39ae-4303-8163-46c57ad220e2.png)

To be confirmed/infirmed and investigated.

**Comment by audrium** [comment]
I confirm that I can reproduce this issue with Kind v0.11.1
