### ISSUE TITLE
rest: workflow can be running when moving files

### ISSUE THREAD

**Issue by mdonadoni** [reanahub/reana-workflow-controller#469]
The `move_files` endpoint makes sure that the workflow is not running before moving the specified files:

https://github.com/reanahub/reana-workflow-controller/blob/9ccc3a93834f3b85799c9fb7f64e7030e9c5757d/reana_workflow_controller/rest/workflows_workspace.py#L601-L605

However, this check is not working correctly:
1. Remove the client-side check in `reana-client`:
    
    ```diff
    --- a/reana_client/cli/files.py
    +++ b/reana_client/cli/files.py
    @@ -521,13 +521,13 @@ def move_files(ctx, source, target, workflow, access_token):  # noqa: D301
     
         if workflow:
             try:
    -            current_status = get_workflow_status(workflow, access_token).get("status")
    -            if current_status == "running":
    -                display_message(
    -                    "File(s) could not be moved for running workflow",
    -                    msg_type="error",
    -                )
    -                sys.exit(1)
                 files = list_files(workflow, access_token)
                 current_files = [file["name"] for file in files]
                 if not any(source in item for item in current_files):
    ```
2. Execute a workflow and move a file while the workflow is running.
3. Check that the file has been moved even though the workflow is still running.

**Comment by mdonadoni** [comment]
Also note that the `delete_files` and `upload_files` endpoints don't have such check, so we should either remove it from `move_files` or add it to both of them, so that every endpoint has the same behaviour.

**Comment by tiborsimko** [comment]
I would say that we should remove the check and empower users who know what they are doing to also execute all these file management commands even whilst the workflow is running. E.g submitting a file during former step for a later step may be common and is perfectly fine (and is already OK), deleting unnecessary big file from a previous step is also perfectly fine (and is already OK), so if someone would like to move some files around for a reason or another, we should allow them to do so. (And we should document the idea that moving of files can be dangerous whilst the workflow is running, so please use with care etc etc for novice users.)
