### ISSUE TITLE
rest: validate paths while managing files

### ISSUE THREAD

**Issue by audrium** [reanahub/reana-workflow-controller#473]
We should improve file path validation while managing files by checking whether paths contain `..` or if they traverse symlinks pointing to files/directories outside the workspace. 

We might also consider having some common utilities to manage files inside workspaces, as we move/copy/delete files and directories in many different places (e.g. fetcher, launcher, retention rules deamon, mv/rm/upload endpoints etc.).

_Originally posted by @mdonadoni in https://github.com/reanahub/reana-workflow-controller/pull/472#discussion_r977663140_

**Comment by mdonadoni** [comment]
Fixed by #479
