### ISSUE TITLE
api: add start workflow endpoint

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-workflow-controller#48]
Originally we discussed in https://github.com/reanahub/reana-client/issues/3 to use `PUT` to an status endpoint, `/api/workflows/{workflow_id}/status` in this case.
- [x] Create new endpoint.
- [x] This new endpoint would replace https://github.com/reanahub/reana-workflow-controller/blob/master/reana_workflow_controller/rest.py#L639-L818, so now we retrieve from DB (see [here](https://github.com/reanahub/reana-workflow-controller/blob/master/reana_workflow_controller/models.py#L64)) all the information needed by the celery task (`workflow_workspace`, `workflow_spec` and `parameters`) and we make the call.
- [x] Add tests for the new endpoint (mock celery if possible otherwise we skip tests for this endpoint)

**Comment by anton-khodak** [comment]
Closed in https://github.com/reanahub/reana-workflow-controller/pull/51https://github.com/reanahub/reana-workflow-controller/pull/51
